const teamCatalog = [
  ['Argentina', 'International', 'International', 'national'],
  ['Croatia', 'International', 'International', 'national'],
  ['Denmark', 'International', 'International', 'national'],
  ['England', 'International', 'International', 'national'],
  ['France', 'International', 'International', 'national'],
  ['Germany', 'International', 'International', 'national'],
  ['Ghana', 'International', 'International', 'national'],
  ['Hungary', 'International', 'International', 'national'],
  ['Italy', 'International', 'International', 'national'],
  ['Mexico', 'International', 'International', 'national'],
  ['Morocco', 'International', 'International', 'national'],
  ['Netherlands', 'International', 'International', 'national'],
  ['Northern Ireland', 'International', 'International', 'national'],
  ['Norway', 'International', 'International', 'national'],
  ['Poland', 'International', 'International', 'national'],
  ['Portugal', 'International', 'International', 'national'],
  ['Republic of Ireland', 'International', 'International', 'national'],
  ['Romania', 'International', 'International', 'national'],
  ['Scotland', 'International', 'International', 'national'],
  ['Spain', 'International', 'International', 'national'],
  ['Sweden', 'International', 'International', 'national'],
  ['Ukraine', 'International', 'International', 'national'],
  ['United States of America', 'International', 'International', 'national'],
  ['Wales', 'International', 'International', 'national'],

  ['Arsenal', 'England', 'Premier League', 'club'],
  ['Aston Villa', 'England', 'Premier League', 'club'],
  ['Bournemouth', 'England', 'Premier League', 'club'],
  ['Brentford', 'England', 'Premier League', 'club'],
  ['Brighton & Hove Albion', 'England', 'Premier League', 'club'],
  ['Burnley', 'England', 'Premier League', 'club'],
  ['Chelsea', 'England', 'Premier League', 'club'],
  ['Crystal Palace', 'England', 'Premier League', 'club'],
  ['Everton', 'England', 'Premier League', 'club'],
  ['Fulham', 'England', 'Premier League', 'club'],
  ['Leeds United', 'England', 'Premier League', 'club'],
  ['Liverpool', 'England', 'Premier League', 'club'],
  ['Manchester City', 'England', 'Premier League', 'club'],
  ['Manchester United', 'England', 'Premier League', 'club'],
  ['Newcastle United', 'England', 'Premier League', 'club'],
  ['Nottingham Forest', 'England', 'Premier League', 'club'],
  ['Sunderland', 'England', 'Premier League', 'club'],
  ['Tottenham Hotspur', 'England', 'Premier League', 'club'],
  ['West Ham United', 'England', 'Premier League', 'club'],
  ['Wolverhampton Wanderers', 'England', 'Premier League', 'club'],

  ['AJ Auxerre', 'France', "Ligue 1 McDonald's", 'club'],
  ['Angers SCO', 'France', "Ligue 1 McDonald's", 'club'],
  ['AS Monaco', 'France', "Ligue 1 McDonald's", 'club'],
  ['Brest', 'France', "Ligue 1 McDonald's", 'club'],
  ['Le Havre', 'France', "Ligue 1 McDonald's", 'club'],
  ['Lens', 'France', "Ligue 1 McDonald's", 'club'],
  ['Lille', 'France', "Ligue 1 McDonald's", 'club'],
  ['Lorient', 'France', "Ligue 1 McDonald's", 'club'],
  ['Lyon', 'France', "Ligue 1 McDonald's", 'club'],
  ['Marseille', 'France', "Ligue 1 McDonald's", 'club'],
  ['Metz', 'France', "Ligue 1 McDonald's", 'club'],
  ['Montpellier', 'France', "Ligue 1 McDonald's", 'club'],
  ['Nantes', 'France', "Ligue 1 McDonald's", 'club'],
  ['Nice', 'France', "Ligue 1 McDonald's", 'club'],
  ['Paris FC', 'France', "Ligue 1 McDonald's", 'club'],
  ['Paris Saint-Germain', 'France', "Ligue 1 McDonald's", 'club'],
  ['Rennes', 'France', "Ligue 1 McDonald's", 'club'],
  ['Strasbourg', 'France', "Ligue 1 McDonald's", 'club'],
  ['Toulouse', 'France', "Ligue 1 McDonald's", 'club'],

  ['1. FC Heidenheim', 'Germany', 'Bundesliga', 'club'],
  ['1. FC Köln', 'Germany', 'Bundesliga', 'club'],
  ['1899 Hoffenheim', 'Germany', 'Bundesliga', 'club'],
  ['Bayer Leverkusen', 'Germany', 'Bundesliga', 'club'],
  ['Bayern Munich', 'Germany', 'Bundesliga', 'club'],
  ['Borussia Dortmund', 'Germany', 'Bundesliga', 'club'],
  ['Borussia Mönchengladbach', 'Germany', 'Bundesliga', 'club'],
  ['Eintracht Frankfurt', 'Germany', 'Bundesliga', 'club'],
  ['FC Augsburg', 'Germany', 'Bundesliga', 'club'],
  ['FC St. Pauli', 'Germany', 'Bundesliga', 'club'],
  ['Hamburger SV', 'Germany', 'Bundesliga', 'club'],
  ['Mainz 05', 'Germany', 'Bundesliga', 'club'],
  ['RB Leipzig', 'Germany', 'Bundesliga', 'club'],
  ['SC Freiburg', 'Germany', 'Bundesliga', 'club'],
  ['Union Berlin', 'Germany', 'Bundesliga', 'club'],
  ['VfB Stuttgart', 'Germany', 'Bundesliga', 'club'],
  ['VfL Wolfsburg', 'Germany', 'Bundesliga', 'club'],
  ['Werder Bremen', 'Germany', 'Bundesliga', 'club'],

  ['AC Milan', 'Italy', 'Serie A Enilive', 'club'],
  ['Atalanta', 'Italy', 'Serie A Enilive', 'club'],
  ['Bologna', 'Italy', 'Serie A Enilive', 'club'],
  ['Cagliari', 'Italy', 'Serie A Enilive', 'club'],
  ['Como', 'Italy', 'Serie A Enilive', 'club'],
  ['Cremonese', 'Italy', 'Serie A Enilive', 'club'],
  ['Fiorentina', 'Italy', 'Serie A Enilive', 'club'],
  ['Genoa', 'Italy', 'Serie A Enilive', 'club'],
  ['Hellas Verona', 'Italy', 'Serie A Enilive', 'club'],
  ['Inter', 'Italy', 'Serie A Enilive', 'club'],
  ['Juventus', 'Italy', 'Serie A Enilive', 'club'],
  ['Lazio', 'Italy', 'Serie A Enilive', 'club'],
  ['Lecce', 'Italy', 'Serie A Enilive', 'club'],
  ['Napoli', 'Italy', 'Serie A Enilive', 'club'],
  ['Parma', 'Italy', 'Serie A Enilive', 'club'],
  ['Pisa', 'Italy', 'Serie A Enilive', 'club'],
  ['Roma', 'Italy', 'Serie A Enilive', 'club'],
  ['Sassuolo', 'Italy', 'Serie A Enilive', 'club'],
  ['Torino', 'Italy', 'Serie A Enilive', 'club'],
  ['Udinese', 'Italy', 'Serie A Enilive', 'club'],

  ['Alavés', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Athletic Club', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Atlético Madrid', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['CA Osasuna', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Celta Vigo', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Elche CF', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['FC Barcelona', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Getafe CF', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Girona FC', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Levante UD', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Rayo Vallecano', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['RC Celta', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['RCD Espanyol', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['RCD Mallorca', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Real Betis', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Real Madrid', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Real Oviedo', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Real Sociedad', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Sevilla FC', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Valencia CF', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Villarreal CF', 'Spain', 'LaLiga EA SPORTS', 'club'],
];

module.exports = { teamCatalog };
