const teamCatalog = [
  ['Argentina', 'International', 'International', 'national'],
  ['Croatia', 'International', 'International', 'national'],
  ['Czechia', 'International', 'International', 'national'],
  ['Denmark', 'International', 'International', 'national'],
  ['England', 'International', 'International', 'national'],
  ['Finland', 'International', 'International', 'national'],
  ['France', 'International', 'International', 'national'],
  ['Germany', 'International', 'International', 'national'],
  ['Ghana', 'International', 'International', 'national'],
  ['Hungary', 'International', 'International', 'national'],
  ['Iceland', 'International', 'International', 'national'],
  ['Italy', 'International', 'International', 'national'],
  ['Mexico', 'International', 'International', 'national'],
  ['Morocco', 'International', 'International', 'national'],
  ['Netherlands', 'International', 'International', 'national'],
  ['Northern Ireland', 'International', 'International', 'national'],
  ['Norway', 'International', 'International', 'national'],
  ['Poland', 'International', 'International', 'national'],
  ['Portugal', 'International', 'International', 'national'],
  ['Qatar', 'International', 'International', 'national'],
  ['Republic of Ireland', 'International', 'International', 'national'],
  ['Romania', 'International', 'International', 'national'],
  ['Scotland', 'International', 'International', 'national'],
  ['Spain', 'International', 'International', 'national'],
  ['Sweden', 'International', 'International', 'national'],
  ['Ukraine', 'International', 'International', 'national'],
  ['United States of America', 'International', 'International', 'national'],
  ['Wales', 'International', 'International', 'national'],
  ['Aldosivi', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Argentinos Juniors', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Atlético Tucumán', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Banfield', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Barracas Central', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Belgrano', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Boca Juniors', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Central Córdoba', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Defensa y Justicia', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Deportivo Riestra', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Estudiantes', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Gimnasia', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Godoy Cruz', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Huracán', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Independiente', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Independiente Rivadavia', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Instituto Córdoba', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Lanús', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Newell\'s Old Boys', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Platense', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Racing Club', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['River Plate', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Rosario Central', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['San Lorenzo', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['San Martín', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Sarmiento', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Talleres', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Tigre', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Unión', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Vélez Sarsfield', 'Argentina', 'Liga Profesional de Fútbol', 'club'],
  ['Austria Klagenfurt', 'Austria', 'Bundesliga', 'club'],
  ['BW Linz', 'Austria', 'Bundesliga', 'club'],
  ['Grazer AK', 'Austria', 'Bundesliga', 'club'],
  ['Hartberg', 'Austria', 'Bundesliga', 'club'],
  ['LASK', 'Austria', 'Bundesliga', 'club'],
  ['Rapid Wien', 'Austria', 'Bundesliga', 'club'],
  ['RB Salzburg', 'Austria', 'Bundesliga', 'club'],
  ['SCR Altach', 'Austria', 'Bundesliga', 'club'],
  ['Sturm Graz', 'Austria', 'Bundesliga', 'club'],
  ['Tirol', 'Austria', 'Bundesliga', 'club'],
  ['TSV Egger Glas Hartberg', 'Austria', 'Bundesliga', 'club'],
  ['Wolfsberger AC', 'Austria', 'Bundesliga', 'club'],
  ['Club Brugge KV', 'Belgium', 'Pro League', 'club'],
  ['KRC Genk', 'Belgium', 'Pro League', 'club'],
  ['Royal Antwerp', 'Belgium', 'Pro League', 'club'],
  ['RSC Anderlecht', 'Belgium', 'Pro League', 'club'],
  ['Union Saint-Gilloise', 'Belgium', 'Pro League', 'club'],
  ['AaB', 'Denmark', '3F Superliga', 'club'],
  ['AGF', 'Denmark', '3F Superliga', 'club'],
  ['Brøndby IF', 'Denmark', '3F Superliga', 'club'],
  ['FC Copenhagen', 'Denmark', '3F Superliga', 'club'],
  ['FC Midtjylland', 'Denmark', '3F Superliga', 'club'],
  ['FC Nordsjælland', 'Denmark', '3F Superliga', 'club'],
  ['Lyngby BK', 'Denmark', '3F Superliga', 'club'],
  ['Randers FC', 'Denmark', '3F Superliga', 'club'],
  ['Silkeborg IF', 'Denmark', '3F Superliga', 'club'],
  ['Sønderjyske', 'Denmark', '3F Superliga', 'club'],
  ['Vejle BK', 'Denmark', '3F Superliga', 'club'],
  ['Viborg FF', 'Denmark', '3F Superliga', 'club'],
  ['Arsenal', 'England', 'Premier League', 'club'],
  ['Aston Villa', 'England', 'Premier League', 'club'],
  ['Bournemouth', 'England', 'Premier League', 'club'],
  ['Brentford', 'England', 'Premier League', 'club'],
  ['Brighton & Hove Albion', 'England', 'Premier League', 'club'],
  ['Burnley', 'England', 'Premier League', 'club'],
  ['Chelsea', 'England', 'Premier League', 'club'],
  ['Crystal Palace', 'England', 'Premier League', 'club'],
  ['Everton', 'England', 'Premier League', 'club'],
  ['Fulham', 'England', 'Premier League', 'club'],
  ['Leeds United', 'England', 'Premier League', 'club'],
  ['Liverpool', 'England', 'Premier League', 'club'],
  ['Manchester City', 'England', 'Premier League', 'club'],
  ['Manchester United', 'England', 'Premier League', 'club'],
  ['Newcastle United', 'England', 'Premier League', 'club'],
  ['Nottingham Forest', 'England', 'Premier League', 'club'],
  ['Sunderland', 'England', 'Premier League', 'club'],
  ['Tottenham Hotspur', 'England', 'Premier League', 'club'],
  ['West Ham United', 'England', 'Premier League', 'club'],
  ['Wolverhampton Wanderers', 'England', 'Premier League', 'club'],
  ['AJ Auxerre', 'France', 'Ligue 1 McDonald\'s', 'club'],
  ['Angers SCO', 'France', 'Ligue 1 McDonald\'s', 'club'],
  ['AS Monaco', 'France', 'Ligue 1 McDonald\'s', 'club'],
  ['Brest', 'France', 'Ligue 1 McDonald\'s', 'club'],
  ['Le Havre', 'France', 'Ligue 1 McDonald\'s', 'club'],
  ['Lens', 'France', 'Ligue 1 McDonald\'s', 'club'],
  ['Lille', 'France', 'Ligue 1 McDonald\'s', 'club'],
  ['Lorient', 'France', 'Ligue 1 McDonald\'s', 'club'],
  ['Lyon', 'France', 'Ligue 1 McDonald\'s', 'club'],
  ['Marseille', 'France', 'Ligue 1 McDonald\'s', 'club'],
  ['Metz', 'France', 'Ligue 1 McDonald\'s', 'club'],
  ['Montpellier', 'France', 'Ligue 1 McDonald\'s', 'club'],
  ['Nantes', 'France', 'Ligue 1 McDonald\'s', 'club'],
  ['Nice', 'France', 'Ligue 1 McDonald\'s', 'club'],
  ['Paris FC', 'France', 'Ligue 1 McDonald\'s', 'club'],
  ['Paris Saint-Germain', 'France', 'Ligue 1 McDonald\'s', 'club'],
  ['Rennes', 'France', 'Ligue 1 McDonald\'s', 'club'],
  ['Strasbourg', 'France', 'Ligue 1 McDonald\'s', 'club'],
  ['Toulouse', 'France', 'Ligue 1 McDonald\'s', 'club'],
  ['1. FC Heidenheim', 'Germany', 'Bundesliga', 'club'],
  ['1. FC Köln', 'Germany', 'Bundesliga', 'club'],
  ['1899 Hoffenheim', 'Germany', 'Bundesliga', 'club'],
  ['Bayer Leverkusen', 'Germany', 'Bundesliga', 'club'],
  ['Bayern Munich', 'Germany', 'Bundesliga', 'club'],
  ['Borussia Dortmund', 'Germany', 'Bundesliga', 'club'],
  ['Borussia Mönchengladbach', 'Germany', 'Bundesliga', 'club'],
  ['Eintracht Frankfurt', 'Germany', 'Bundesliga', 'club'],
  ['FC Augsburg', 'Germany', 'Bundesliga', 'club'],
  ['FC St. Pauli', 'Germany', 'Bundesliga', 'club'],
  ['Hamburger SV', 'Germany', 'Bundesliga', 'club'],
  ['Mainz 05', 'Germany', 'Bundesliga', 'club'],
  ['RB Leipzig', 'Germany', 'Bundesliga', 'club'],
  ['SC Freiburg', 'Germany', 'Bundesliga', 'club'],
  ['Union Berlin', 'Germany', 'Bundesliga', 'club'],
  ['VfB Stuttgart', 'Germany', 'Bundesliga', 'club'],
  ['VfL Wolfsburg', 'Germany', 'Bundesliga', 'club'],
  ['Werder Bremen', 'Germany', 'Bundesliga', 'club'],
  ['Bohemians', 'Ireland', 'SSE Airtricity PD', 'club'],
  ['Cork City', 'Ireland', 'SSE Airtricity PD', 'club'],
  ['Derry City', 'Ireland', 'SSE Airtricity PD', 'club'],
  ['Drogheda United', 'Ireland', 'SSE Airtricity PD', 'club'],
  ['Galway United', 'Ireland', 'SSE Airtricity PD', 'club'],
  ['Shamrock Rovers', 'Ireland', 'SSE Airtricity PD', 'club'],
  ['Shelbourne', 'Ireland', 'SSE Airtricity PD', 'club'],
  ['Sligo Rovers', 'Ireland', 'SSE Airtricity PD', 'club'],
  ['St Patrick\'s Athletic', 'Ireland', 'SSE Airtricity PD', 'club'],
  ['Waterford', 'Ireland', 'SSE Airtricity PD', 'club'],
  ['AC Milan', 'Italy', 'Serie A Enilive', 'club'],
  ['Atalanta', 'Italy', 'Serie A Enilive', 'club'],
  ['Bologna', 'Italy', 'Serie A Enilive', 'club'],
  ['Cagliari', 'Italy', 'Serie A Enilive', 'club'],
  ['Como', 'Italy', 'Serie A Enilive', 'club'],
  ['Cremonese', 'Italy', 'Serie A Enilive', 'club'],
  ['Fiorentina', 'Italy', 'Serie A Enilive', 'club'],
  ['Genoa', 'Italy', 'Serie A Enilive', 'club'],
  ['Hellas Verona', 'Italy', 'Serie A Enilive', 'club'],
  ['Inter', 'Italy', 'Serie A Enilive', 'club'],
  ['Juventus', 'Italy', 'Serie A Enilive', 'club'],
  ['Lazio', 'Italy', 'Serie A Enilive', 'club'],
  ['Lecce', 'Italy', 'Serie A Enilive', 'club'],
  ['Napoli', 'Italy', 'Serie A Enilive', 'club'],
  ['Parma', 'Italy', 'Serie A Enilive', 'club'],
  ['Pisa', 'Italy', 'Serie A Enilive', 'club'],
  ['Roma', 'Italy', 'Serie A Enilive', 'club'],
  ['Sassuolo', 'Italy', 'Serie A Enilive', 'club'],
  ['Torino', 'Italy', 'Serie A Enilive', 'club'],
  ['Udinese', 'Italy', 'Serie A Enilive', 'club'],
  ['Chivas', 'Mexico', 'Liga MX', 'club'],
  ['Club América', 'Mexico', 'Liga MX', 'club'],
  ['Cruz Azul', 'Mexico', 'Liga MX', 'club'],
  ['Monterrey', 'Mexico', 'Liga MX', 'club'],
  ['Tigres UANL', 'Mexico', 'Liga MX', 'club'],
  ['Ajax', 'Netherlands', 'Eredivisie', 'club'],
  ['AZ', 'Netherlands', 'Eredivisie', 'club'],
  ['Excelsior', 'Netherlands', 'Eredivisie', 'club'],
  ['FC Groningen', 'Netherlands', 'Eredivisie', 'club'],
  ['FC Twente', 'Netherlands', 'Eredivisie', 'club'],
  ['FC Utrecht', 'Netherlands', 'Eredivisie', 'club'],
  ['Feyenoord', 'Netherlands', 'Eredivisie', 'club'],
  ['Fortuna Sittard', 'Netherlands', 'Eredivisie', 'club'],
  ['Go Ahead Eagles', 'Netherlands', 'Eredivisie', 'club'],
  ['Heracles Almelo', 'Netherlands', 'Eredivisie', 'club'],
  ['NAC Breda', 'Netherlands', 'Eredivisie', 'club'],
  ['NEC Nijmegen', 'Netherlands', 'Eredivisie', 'club'],
  ['PEC Zwolle', 'Netherlands', 'Eredivisie', 'club'],
  ['PSV', 'Netherlands', 'Eredivisie', 'club'],
  ['SC Heerenveen', 'Netherlands', 'Eredivisie', 'club'],
  ['Sparta Rotterdam', 'Netherlands', 'Eredivisie', 'club'],
  ['Telstar', 'Netherlands', 'Eredivisie', 'club'],
  ['Willem II', 'Netherlands', 'Eredivisie', 'club'],
  ['Bodø/Glimt', 'Norway', 'Eliteserien', 'club'],
  ['Brann', 'Norway', 'Eliteserien', 'club'],
  ['Bryne', 'Norway', 'Eliteserien', 'club'],
  ['Fredrikstad', 'Norway', 'Eliteserien', 'club'],
  ['HamKam', 'Norway', 'Eliteserien', 'club'],
  ['Haugesund', 'Norway', 'Eliteserien', 'club'],
  ['KFUM Oslo', 'Norway', 'Eliteserien', 'club'],
  ['Kristiansund', 'Norway', 'Eliteserien', 'club'],
  ['Molde', 'Norway', 'Eliteserien', 'club'],
  ['Rosenborg', 'Norway', 'Eliteserien', 'club'],
  ['Sandefjord', 'Norway', 'Eliteserien', 'club'],
  ['Sarpsborg 08', 'Norway', 'Eliteserien', 'club'],
  ['Strømsgodset', 'Norway', 'Eliteserien', 'club'],
  ['Tromsø', 'Norway', 'Eliteserien', 'club'],
  ['Viking', 'Norway', 'Eliteserien', 'club'],
  ['Vålerenga', 'Norway', 'Eliteserien', 'club'],
  ['Arka Gdynia', 'Poland', 'PKO BP Ekstraklasa', 'club'],
  ['Cracovia', 'Poland', 'PKO BP Ekstraklasa', 'club'],
  ['GKS Katowice', 'Poland', 'PKO BP Ekstraklasa', 'club'],
  ['Górnik Zabrze', 'Poland', 'PKO BP Ekstraklasa', 'club'],
  ['Jagiellonia Białystok', 'Poland', 'PKO BP Ekstraklasa', 'club'],
  ['Korona Kielce', 'Poland', 'PKO BP Ekstraklasa', 'club'],
  ['Lech Poznań', 'Poland', 'PKO BP Ekstraklasa', 'club'],
  ['Lechia Gdańsk', 'Poland', 'PKO BP Ekstraklasa', 'club'],
  ['Legia Warszawa', 'Poland', 'PKO BP Ekstraklasa', 'club'],
  ['Motor Lublin', 'Poland', 'PKO BP Ekstraklasa', 'club'],
  ['Piast Gliwice', 'Poland', 'PKO BP Ekstraklasa', 'club'],
  ['Pogoń Szczecin', 'Poland', 'PKO BP Ekstraklasa', 'club'],
  ['Puszcza Niepołomice', 'Poland', 'PKO BP Ekstraklasa', 'club'],
  ['Radomiak Radom', 'Poland', 'PKO BP Ekstraklasa', 'club'],
  ['Raków Częstochowa', 'Poland', 'PKO BP Ekstraklasa', 'club'],
  ['Stal Mielec', 'Poland', 'PKO BP Ekstraklasa', 'club'],
  ['Widzew Łódź', 'Poland', 'PKO BP Ekstraklasa', 'club'],
  ['Zagłębie Lubin', 'Poland', 'PKO BP Ekstraklasa', 'club'],
  ['AVS', 'Portugal', 'Liga Portugal', 'club'],
  ['Braga', 'Portugal', 'Liga Portugal', 'club'],
  ['Casa Pia', 'Portugal', 'Liga Portugal', 'club'],
  ['Estoril Praia', 'Portugal', 'Liga Portugal', 'club'],
  ['FC Alverca', 'Portugal', 'Liga Portugal', 'club'],
  ['FC Arouca', 'Portugal', 'Liga Portugal', 'club'],
  ['FC Famalicão', 'Portugal', 'Liga Portugal', 'club'],
  ['FC Porto', 'Portugal', 'Liga Portugal', 'club'],
  ['Gil Vicente', 'Portugal', 'Liga Portugal', 'club'],
  ['Moreirense', 'Portugal', 'Liga Portugal', 'club'],
  ['Nacional', 'Portugal', 'Liga Portugal', 'club'],
  ['Rio Ave', 'Portugal', 'Liga Portugal', 'club'],
  ['Santa Clara', 'Portugal', 'Liga Portugal', 'club'],
  ['SL Benfica', 'Portugal', 'Liga Portugal', 'club'],
  ['Sporting CP', 'Portugal', 'Liga Portugal', 'club'],
  ['Tondela', 'Portugal', 'Liga Portugal', 'club'],
  ['Vitória SC', 'Portugal', 'Liga Portugal', 'club'],
  ['Botoșani', 'Romania', 'SuperLiga', 'club'],
  ['CFR Cluj', 'Romania', 'SuperLiga', 'club'],
  ['Dinamo București', 'Romania', 'SuperLiga', 'club'],
  ['Farul Constanța', 'Romania', 'SuperLiga', 'club'],
  ['FCSB', 'Romania', 'SuperLiga', 'club'],
  ['Hermannstadt', 'Romania', 'SuperLiga', 'club'],
  ['Metaloglobus', 'Romania', 'SuperLiga', 'club'],
  ['Oțelul Galați', 'Romania', 'SuperLiga', 'club'],
  ['Petrolul Ploiești', 'Romania', 'SuperLiga', 'club'],
  ['Poli Iași', 'Romania', 'SuperLiga', 'club'],
  ['Rapid București', 'Romania', 'SuperLiga', 'club'],
  ['Sepsi OSK', 'Romania', 'SuperLiga', 'club'],
  ['U Cluj', 'Romania', 'SuperLiga', 'club'],
  ['Unirea Slobozia', 'Romania', 'SuperLiga', 'club'],
  ['Universitatea Craiova', 'Romania', 'SuperLiga', 'club'],
  ['UTA Arad', 'Romania', 'SuperLiga', 'club'],
  ['Al Ahli', 'Saudi Arabia', 'Saudi Pro League', 'club'],
  ['Al Hilal', 'Saudi Arabia', 'Saudi Pro League', 'club'],
  ['Al Ittihad', 'Saudi Arabia', 'Saudi Pro League', 'club'],
  ['Al Nassr', 'Saudi Arabia', 'Saudi Pro League', 'club'],
  ['Celtic', 'Scotland', 'Scottish Premiership', 'club'],
  ['Heart of Midlothian', 'Scotland', 'Scottish Premiership', 'club'],
  ['Hibernian', 'Scotland', 'Scottish Premiership', 'club'],
  ['Rangers', 'Scotland', 'Scottish Premiership', 'club'],
  ['Alavés', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Athletic Club', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Atlético Madrid', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['CA Osasuna', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Celta Vigo', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Elche CF', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['FC Barcelona', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Getafe CF', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Girona FC', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Levante UD', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Rayo Vallecano', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['RC Celta', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['RCD Espanyol', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['RCD Mallorca', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Real Betis', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Real Madrid', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Real Oviedo', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Real Sociedad', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Sevilla FC', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Valencia CF', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Villarreal CF', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['AIK', 'Sweden', 'Allsvenskan', 'club'],
  ['BK Häcken', 'Sweden', 'Allsvenskan', 'club'],
  ['Brommapojkarna', 'Sweden', 'Allsvenskan', 'club'],
  ['Degerfors', 'Sweden', 'Allsvenskan', 'club'],
  ['Djurgårdens IF', 'Sweden', 'Allsvenskan', 'club'],
  ['GAIS', 'Sweden', 'Allsvenskan', 'club'],
  ['Halmstads BK', 'Sweden', 'Allsvenskan', 'club'],
  ['Hammarby IF', 'Sweden', 'Allsvenskan', 'club'],
  ['IF Elfsborg', 'Sweden', 'Allsvenskan', 'club'],
  ['IFK Göteborg', 'Sweden', 'Allsvenskan', 'club'],
  ['IFK Norrköping', 'Sweden', 'Allsvenskan', 'club'],
  ['IK Sirius', 'Sweden', 'Allsvenskan', 'club'],
  ['Malmö FF', 'Sweden', 'Allsvenskan', 'club'],
  ['Mjällby AIF', 'Sweden', 'Allsvenskan', 'club'],
  ['Värnamo', 'Sweden', 'Allsvenskan', 'club'],
  ['Östers IF', 'Sweden', 'Allsvenskan', 'club'],
  ['Basel', 'Switzerland', 'Credit Suisse Super League', 'club'],
  ['Grasshopper Club', 'Switzerland', 'Credit Suisse Super League', 'club'],
  ['Lausanne-Sport', 'Switzerland', 'Credit Suisse Super League', 'club'],
  ['Lugano', 'Switzerland', 'Credit Suisse Super League', 'club'],
  ['Luzern', 'Switzerland', 'Credit Suisse Super League', 'club'],
  ['Servette', 'Switzerland', 'Credit Suisse Super League', 'club'],
  ['Sion', 'Switzerland', 'Credit Suisse Super League', 'club'],
  ['St. Gallen', 'Switzerland', 'Credit Suisse Super League', 'club'],
  ['Winterthur', 'Switzerland', 'Credit Suisse Super League', 'club'],
  ['Young Boys', 'Switzerland', 'Credit Suisse Super League', 'club'],
  ['Yverdon Sport', 'Switzerland', 'Credit Suisse Super League', 'club'],
  ['Zürich', 'Switzerland', 'Credit Suisse Super League', 'club'],
  ['Alanyaspor', 'Türkiye', 'Süper Lig', 'club'],
  ['Antalyaspor', 'Türkiye', 'Süper Lig', 'club'],
  ['Başakşehir', 'Türkiye', 'Süper Lig', 'club'],
  ['Beşiktaş', 'Türkiye', 'Süper Lig', 'club'],
  ['Eyüpspor', 'Türkiye', 'Süper Lig', 'club'],
  ['Fenerbahçe', 'Türkiye', 'Süper Lig', 'club'],
  ['Galatasaray', 'Türkiye', 'Süper Lig', 'club'],
  ['Gaziantep FK', 'Türkiye', 'Süper Lig', 'club'],
  ['Gençlerbirliği', 'Türkiye', 'Süper Lig', 'club'],
  ['Göztepe', 'Türkiye', 'Süper Lig', 'club'],
  ['Kasımpaşa', 'Türkiye', 'Süper Lig', 'club'],
  ['Kayserispor', 'Türkiye', 'Süper Lig', 'club'],
  ['Kocaelispor', 'Türkiye', 'Süper Lig', 'club'],
  ['Samsunspor', 'Türkiye', 'Süper Lig', 'club'],
  ['Trabzonspor', 'Türkiye', 'Süper Lig', 'club'],
  ['Çaykur Rizespor', 'Türkiye', 'Süper Lig', 'club'],
  ['Atlanta United', 'USA', 'MLS', 'club'],
  ['Austin FC', 'USA', 'MLS', 'club'],
  ['CF Montréal', 'USA', 'MLS', 'club'],
  ['Charlotte FC', 'USA', 'MLS', 'club'],
  ['Chicago Fire', 'USA', 'MLS', 'club'],
  ['Colorado Rapids', 'USA', 'MLS', 'club'],
  ['Columbus Crew', 'USA', 'MLS', 'club'],
  ['DC United', 'USA', 'MLS', 'club'],
  ['FC Cincinnati', 'USA', 'MLS', 'club'],
  ['FC Dallas', 'USA', 'MLS', 'club'],
  ['Houston Dynamo', 'USA', 'MLS', 'club'],
  ['Inter Miami', 'USA', 'MLS', 'club'],
  ['LA Galaxy', 'USA', 'MLS', 'club'],
  ['Los Angeles FC', 'USA', 'MLS', 'club'],
  ['Minnesota United', 'USA', 'MLS', 'club'],
  ['Nashville SC', 'USA', 'MLS', 'club'],
  ['New England Revolution', 'USA', 'MLS', 'club'],
  ['New York City FC', 'USA', 'MLS', 'club'],
  ['New York Red Bulls', 'USA', 'MLS', 'club'],
  ['Orlando City', 'USA', 'MLS', 'club'],
  ['Philadelphia Union', 'USA', 'MLS', 'club'],
  ['Portland Timbers', 'USA', 'MLS', 'club'],
  ['Real Salt Lake', 'USA', 'MLS', 'club'],
  ['San Diego FC', 'USA', 'MLS', 'club'],
  ['San Jose Earthquakes', 'USA', 'MLS', 'club'],
  ['Seattle Sounders', 'USA', 'MLS', 'club'],
  ['Sporting Kansas City', 'USA', 'MLS', 'club'],
  ['St. Louis City SC', 'USA', 'MLS', 'club'],
  ['Toronto FC', 'USA', 'MLS', 'club'],
  ['Vancouver Whitecaps', 'USA', 'MLS', 'club'],
];

module.exports = { teamCatalog };
