const teamCatalog = [
  // International
  ['Argentina', 'International', 'International', 'national'],
  ['Croatia', 'International', 'International', 'national'],
  ['Czechia', 'International', 'International', 'national'],
  ['Denmark', 'International', 'International', 'national'],
  ['England', 'International', 'International', 'national'],
  ['Finland', 'International', 'International', 'national'],
  ['France', 'International', 'International', 'national'],
  ['Germany', 'International', 'International', 'national'],
  ['Ghana', 'International', 'International', 'national'],
  ['Hungary', 'International', 'International', 'national'],
  ['Iceland', 'International', 'International', 'national'],
  ['Italy', 'International', 'International', 'national'],
  ['Mexico', 'International', 'International', 'national'],
  ['Morocco', 'International', 'International', 'national'],
  ['Netherlands', 'International', 'International', 'national'],
  ['Northern Ireland', 'International', 'International', 'national'],
  ['Norway', 'International', 'International', 'national'],
  ['Poland', 'International', 'International', 'national'],
  ['Portugal', 'International', 'International', 'national'],
  ['Qatar', 'International', 'International', 'national'],
  ['Republic of Ireland', 'International', 'International', 'national'],
  ['Romania', 'International', 'International', 'national'],
  ['Scotland', 'International', 'International', 'national'],
  ['Spain', 'International', 'International', 'national'],
  ['Sweden', 'International', 'International', 'national'],
  ['Ukraine', 'International', 'International', 'national'],
  ['United States of America', 'International', 'International', 'national'],
  ['Wales', 'International', 'International', 'national'],

  // England - Premier League
  ['Arsenal', 'England', 'Premier League', 'club'],
  ['Aston Villa', 'England', 'Premier League', 'club'],
  ['Bournemouth', 'England', 'Premier League', 'club'],
  ['Brentford', 'England', 'Premier League', 'club'],
  ['Brighton & Hove Albion', 'England', 'Premier League', 'club'],
  ['Burnley', 'England', 'Premier League', 'club'],
  ['Chelsea', 'England', 'Premier League', 'club'],
  ['Crystal Palace', 'England', 'Premier League', 'club'],
  ['Everton', 'England', 'Premier League', 'club'],
  ['Fulham', 'England', 'Premier League', 'club'],
  ['Leeds United', 'England', 'Premier League', 'club'],
  ['Liverpool', 'England', 'Premier League', 'club'],
  ['Manchester City', 'England', 'Premier League', 'club'],
  ['Manchester United', 'England', 'Premier League', 'club'],
  ['Newcastle United', 'England', 'Premier League', 'club'],
  ['Nottingham Forest', 'England', 'Premier League', 'club'],
  ['Sunderland', 'England', 'Premier League', 'club'],
  ['Tottenham Hotspur', 'England', 'Premier League', 'club'],
  ['West Ham United', 'England', 'Premier League', 'club'],
  ['Wolverhampton Wanderers', 'England', 'Premier League', 'club'],

  // Spain - LaLiga
  ['Alavés', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Athletic Club', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Atlético Madrid', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['CA Osasuna', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Celta Vigo', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Elche CF', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['FC Barcelona', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Getafe CF', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Girona FC', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Levante UD', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Rayo Vallecano', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['RC Celta', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['RCD Espanyol', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['RCD Mallorca', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Real Betis', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Real Madrid', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Real Oviedo', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Real Sociedad', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Sevilla FC', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Valencia CF', 'Spain', 'LaLiga EA SPORTS', 'club'],
  ['Villarreal CF', 'Spain', 'LaLiga EA SPORTS', 'club'],

  // Germany - Bundesliga
  ['1. FC Heidenheim', 'Germany', 'Bundesliga', 'club'],
  ['1. FC Köln', 'Germany', 'Bundesliga', 'club'],
  ['1899 Hoffenheim', 'Germany', 'Bundesliga', 'club'],
  ['Bayer Leverkusen', 'Germany', 'Bundesliga', 'club'],
  ['Bayern Munich', 'Germany', 'Bundesliga', 'club'],
  ['Borussia Dortmund', 'Germany', 'Bundesliga', 'club'],
  ['Borussia Mönchengladbach', 'Germany', 'Bundesliga', 'club'],
  ['Eintracht Frankfurt', 'Germany', 'Bundesliga', 'club'],
  ['FC Augsburg', 'Germany', 'Bundesliga', 'club'],
  ['FC St. Pauli', 'Germany', 'Bundesliga', 'club'],
  ['Hamburger SV', 'Germany', 'Bundesliga', 'club'],
  ['Mainz 05', 'Germany', 'Bundesliga', 'club'],
  ['RB Leipzig', 'Germany', 'Bundesliga', 'club'],
  ['SC Freiburg', 'Germany', 'Bundesliga', 'club'],
  ['Union Berlin', 'Germany', 'Bundesliga', 'club'],
  ['VfB Stuttgart', 'Germany', 'Bundesliga', 'club'],
  ['VfL Wolfsburg', 'Germany', 'Bundesliga', 'club'],
  ['Werder Bremen', 'Germany', 'Bundesliga', 'club'],

  // Italy - Serie A
  ['AC Milan', 'Italy', 'Serie A Enilive', 'club'],
  ['Atalanta', 'Italy', 'Serie A Enilive', 'club'],
  ['Bologna', 'Italy', 'Serie A Enilive', 'club'],
  ['Cagliari', 'Italy', 'Serie A Enilive', 'club'],
  ['Como', 'Italy', 'Serie A Enilive', 'club'],
  ['Cremonese', 'Italy', 'Serie A Enilive', 'club'],
  ['Fiorentina', 'Italy', 'Serie A Enilive', 'club'],
  ['Genoa', 'Italy', 'Serie A Enilive', 'club'],
  ['Hellas Verona', 'Italy', 'Serie A Enilive', 'club'],
  ['Inter', 'Italy', 'Serie A Enilive', 'club'],
  ['Juventus', 'Italy', 'Serie A Enilive', 'club'],
  ['Lazio', 'Italy', 'Serie A Enilive', 'club'],
  ['Lecce', 'Italy', 'Serie A Enilive', 'club'],
  ['Napoli', 'Italy', 'Serie A Enilive', 'club'],
  ['Parma', 'Italy', 'Serie A Enilive', 'club'],
  ['Pisa', 'Italy', 'Serie A Enilive', 'club'],
  ['Roma', 'Italy', 'Serie A Enilive', 'club'],
  ['Sassuolo', 'Italy', 'Serie A Enilive', 'club'],
  ['Torino', 'Italy', 'Serie A Enilive', 'club'],
  ['Udinese', 'Italy', 'Serie A Enilive', 'club'],

  // France - Ligue 1
  ['AJ Auxerre', 'France', "Ligue 1 McDonald's", 'club'],
  ['AS Monaco', 'France', "Ligue 1 McDonald's", 'club'],
  ['Angers SCO', 'France', "Ligue 1 McDonald's", 'club'],
  ['FC Lorient', 'France', "Ligue 1 McDonald's", 'club'],
  ['FC Metz', 'France', "Ligue 1 McDonald's", 'club'],
  ['Le Havre AC', 'France', "Ligue 1 McDonald's", 'club'],
  ['LOSC Lille', 'France', "Ligue 1 McDonald's", 'club'],
  ['Olympique Lyonnais', 'France', "Ligue 1 McDonald's", 'club'],
  ['Olympique de Marseille', 'France', "Ligue 1 McDonald's", 'club'],
  ['OGC Nice', 'France', "Ligue 1 McDonald's", 'club'],
  ['Paris FC', 'France', "Ligue 1 McDonald's", 'club'],
  ['Paris Saint-Germain', 'France', "Ligue 1 McDonald's", 'club'],
  ['RC Lens', 'France', "Ligue 1 McDonald's", 'club'],
  ['RC Strasbourg', 'France', "Ligue 1 McDonald's", 'club'],
  ['Stade Brestois 29', 'France', "Ligue 1 McDonald's", 'club'],
  ['Stade Rennais', 'France', "Ligue 1 McDonald's", 'club'],
  ['Toulouse FC', 'France', "Ligue 1 McDonald's", 'club'],

  // Netherlands - Eredivisie
  ['Ajax', 'Netherlands', 'Eredivisie', 'club'],
  ['AZ', 'Netherlands', 'Eredivisie', 'club'],
  ['Excelsior', 'Netherlands', 'Eredivisie', 'club'],
  ['FC Groningen', 'Netherlands', 'Eredivisie', 'club'],
  ['FC Twente', 'Netherlands', 'Eredivisie', 'club'],
  ['FC Utrecht', 'Netherlands', 'Eredivisie', 'club'],
  ['Feyenoord', 'Netherlands', 'Eredivisie', 'club'],
  ['Fortuna Sittard', 'Netherlands', 'Eredivisie', 'club'],
  ['Go Ahead Eagles', 'Netherlands', 'Eredivisie', 'club'],
  ['Heracles Almelo', 'Netherlands', 'Eredivisie', 'club'],
  ['NAC Breda', 'Netherlands', 'Eredivisie', 'club'],
  ['NEC Nijmegen', 'Netherlands', 'Eredivisie', 'club'],
  ['PEC Zwolle', 'Netherlands', 'Eredivisie', 'club'],
  ['PSV', 'Netherlands', 'Eredivisie', 'club'],
  ['SC Heerenveen', 'Netherlands', 'Eredivisie', 'club'],
  ['Sparta Rotterdam', 'Netherlands', 'Eredivisie', 'club'],
  ['Telstar', 'Netherlands', 'Eredivisie', 'club'],
  ['Willem II', 'Netherlands', 'Eredivisie', 'club'],

  // Portugal - Liga Portugal
  ['AVS', 'Portugal', 'Liga Portugal', 'club'],
  ['Braga', 'Portugal', 'Liga Portugal', 'club'],
  ['Casa Pia', 'Portugal', 'Liga Portugal', 'club'],
  ['Estoril Praia', 'Portugal', 'Liga Portugal', 'club'],
  ['FC Alverca', 'Portugal', 'Liga Portugal', 'club'],
  ['FC Arouca', 'Portugal', 'Liga Portugal', 'club'],
  ['FC Famalicão', 'Portugal', 'Liga Portugal', 'club'],
  ['FC Porto', 'Portugal', 'Liga Portugal', 'club'],
  ['Gil Vicente', 'Portugal', 'Liga Portugal', 'club'],
  ['Moreirense', 'Portugal', 'Liga Portugal', 'club'],
  ['Nacional', 'Portugal', 'Liga Portugal', 'club'],
  ['Rio Ave', 'Portugal', 'Liga Portugal', 'club'],
  ['Santa Clara', 'Portugal', 'Liga Portugal', 'club'],
  ['SL Benfica', 'Portugal', 'Liga Portugal', 'club'],
  ['Sporting CP', 'Portugal', 'Liga Portugal', 'club'],
  ['Tondela', 'Portugal', 'Liga Portugal', 'club'],
  ['Vitória SC', 'Portugal', 'Liga Portugal', 'club'],

  // Turkey - Super Lig
  ['Alanyaspor', 'Türkiye', 'Süper Lig', 'club'],
  ['Antalyaspor', 'Türkiye', 'Süper Lig', 'club'],
  ['Başakşehir', 'Türkiye', 'Süper Lig', 'club'],
  ['Beşiktaş', 'Türkiye', 'Süper Lig', 'club'],
  ['Çaykur Rizespor', 'Türkiye', 'Süper Lig', 'club'],
  ['Eyüpspor', 'Türkiye', 'Süper Lig', 'club'],
  ['Fenerbahçe', 'Türkiye', 'Süper Lig', 'club'],
  ['Galatasaray', 'Türkiye', 'Süper Lig', 'club'],
  ['Gaziantep FK', 'Türkiye', 'Süper Lig', 'club'],
  ['Gençlerbirliği', 'Türkiye', 'Süper Lig', 'club'],
  ['Göztepe', 'Türkiye', 'Süper Lig', 'club'],
  ['Kasımpaşa', 'Türkiye', 'Süper Lig', 'club'],
  ['Kayserispor', 'Türkiye', 'Süper Lig', 'club'],
  ['Kocaelispor', 'Türkiye', 'Süper Lig', 'club'],
  ['Samsunspor', 'Türkiye', 'Süper Lig', 'club'],
  ['Trabzonspor', 'Türkiye', 'Süper Lig', 'club'],

  // Czechia - Chance Liga
  ['Baník Ostrava', 'Czechia', 'Chance Liga', 'club'],
  ['Bohemians Praha 1905', 'Czechia', 'Chance Liga', 'club'],
  ['Dukla Praha', 'Czechia', 'Chance Liga', 'club'],
  ['FC Hradec Králové', 'Czechia', 'Chance Liga', 'club'],
  ['FC Slovan Liberec', 'Czechia', 'Chance Liga', 'club'],
  ['FC Zlín', 'Czechia', 'Chance Liga', 'club'],
  ['FK Jablonec', 'Czechia', 'Chance Liga', 'club'],
  ['MFK Karviná', 'Czechia', 'Chance Liga', 'club'],
  ['Pardubice', 'Czechia', 'Chance Liga', 'club'],
  ['Sigma Olomouc', 'Czechia', 'Chance Liga', 'club'],
  ['Slavia Praha', 'Czechia', 'Chance Liga', 'club'],
  ['Slovacko', 'Czechia', 'Chance Liga', 'club'],
  ['Sparta Praha', 'Czechia', 'Chance Liga', 'club'],
  ['Teplice', 'Czechia', 'Chance Liga', 'club'],
  ['Viktoria Plzeň', 'Czechia', 'Chance Liga', 'club'],

  // USA - MLS (popular complete-ish set)
  ['Atlanta United', 'USA', 'MLS', 'club'],
  ['Austin FC', 'USA', 'MLS', 'club'],
  ['CF Montréal', 'USA', 'MLS', 'club'],
  ['Charlotte FC', 'USA', 'MLS', 'club'],
  ['Chicago Fire', 'USA', 'MLS', 'club'],
  ['Colorado Rapids', 'USA', 'MLS', 'club'],
  ['Columbus Crew', 'USA', 'MLS', 'club'],
  ['DC United', 'USA', 'MLS', 'club'],
  ['FC Cincinnati', 'USA', 'MLS', 'club'],
  ['FC Dallas', 'USA', 'MLS', 'club'],
  ['Houston Dynamo', 'USA', 'MLS', 'club'],
  ['Inter Miami', 'USA', 'MLS', 'club'],
  ['LA Galaxy', 'USA', 'MLS', 'club'],
  ['Los Angeles FC', 'USA', 'MLS', 'club'],
  ['Minnesota United', 'USA', 'MLS', 'club'],
  ['Nashville SC', 'USA', 'MLS', 'club'],
  ['New England Revolution', 'USA', 'MLS', 'club'],
  ['New York City FC', 'USA', 'MLS', 'club'],
  ['New York Red Bulls', 'USA', 'MLS', 'club'],
  ['Orlando City', 'USA', 'MLS', 'club'],
  ['Philadelphia Union', 'USA', 'MLS', 'club'],
  ['Portland Timbers', 'USA', 'MLS', 'club'],
  ['Real Salt Lake', 'USA', 'MLS', 'club'],
  ['San Diego FC', 'USA', 'MLS', 'club'],
  ['San Jose Earthquakes', 'USA', 'MLS', 'club'],
  ['Seattle Sounders', 'USA', 'MLS', 'club'],
  ['Sporting Kansas City', 'USA', 'MLS', 'club'],
  ['St. Louis City SC', 'USA', 'MLS', 'club'],
  ['Toronto FC', 'USA', 'MLS', 'club'],
  ['Vancouver Whitecaps', 'USA', 'MLS', 'club'],

  // Additional leagues already used in the app historically
  ['Club Brugge KV', 'Belgium', 'Pro League', 'club'],
  ['Union Saint-Gilloise', 'Belgium', 'Pro League', 'club'],
  ['KRC Genk', 'Belgium', 'Pro League', 'club'],
  ['RSC Anderlecht', 'Belgium', 'Pro League', 'club'],
  ['Royal Antwerp', 'Belgium', 'Pro League', 'club'],
  ['Celtic', 'Scotland', 'Scottish Premiership', 'club'],
  ['Rangers', 'Scotland', 'Scottish Premiership', 'club'],
  ['Hibernian', 'Scotland', 'Scottish Premiership', 'club'],
  ['Heart of Midlothian', 'Scotland', 'Scottish Premiership', 'club'],
  ['Club América', 'Mexico', 'Liga MX', 'club'],
  ['Chivas', 'Mexico', 'Liga MX', 'club'],
  ['Cruz Azul', 'Mexico', 'Liga MX', 'club'],
  ['Monterrey', 'Mexico', 'Liga MX', 'club'],
  ['Tigres UANL', 'Mexico', 'Liga MX', 'club'],
  ['Al Hilal', 'Saudi Arabia', 'Saudi Pro League', 'club'],
  ['Al Nassr', 'Saudi Arabia', 'Saudi Pro League', 'club'],
  ['Al Ittihad', 'Saudi Arabia', 'Saudi Pro League', 'club'],
  ['Al Ahli', 'Saudi Arabia', 'Saudi Pro League', 'club']
];

module.exports = { teamCatalog };
